#--------------------------------------------系统端口--------------------
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineShop?characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #禁止那些ip
       # deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
#----------------------------------------------mybatis----------------------------------------------
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.onlineShop.bean
#全局映射器启用缓存
  configuration:
    cache-enabled: true
#查询时,关闭关联对象及时加载以提高性能
    lazy-loading-enabled: false
#按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    aggressive-lazy-loading: false
#允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
#对于批量更新操作缓存SQL以提高性能
    default-executor-type: REUSE
#数据库执行超时时间
    default-statement-timeout: 25000
#开启驼峰识别
    map-underscore-to-camel-case: true


#----------------------------------------------日志输出----------------------------------------------
logging:
  config: config/logback.xml

